docs: IFS-?? language changes
IsyFact/isy-bedienkonzept pull request #4
Opened 2024-09-03 11:23 UTC by msg-jstren

2024-09-27 09:23 UTC, GrosseNe submitted a review, later dismissed

2024-09-27 09:23 UTC, GrosseNe commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
>  //ToDo: Das wiederspricht sich doch. Im Satz darüber wird doch beschrieben, dass beide Buttonvarianten zusammen genutzt werden.
ToDo erledigt

2024-09-27 09:23 UTC, GrosseNe commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
>  //ToDo: Soll das heißen, dass das die Farbe der Links bei Bedarf geändert werden darf? Dann sollte das auch so geschrieben werden
ToDo erledigt

2024-09-27 09:23 UTC, GrosseNe commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
>  //TODO: Ist die Verneinung richtig. Wenn ja, earum?
Ich finde die Empfehlung, dass Listeneinträge nicht als ganze Sätze formuliert sein sollen, schwierig. Das geht ja sehr stark ins inhaltliche rein und kann ja sehr wohl sinnvoll sein : siehe diese Liste hier, die vollständige Sätze enthält.

2024-09-27 09:23 UTC, GrosseNe commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
>  //ToDo: Abschnitt nicht verständlich
ToDo erledigt

2024-09-27 09:23 UTC, GrosseNe commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
>  //ToDo: Nicht verständlich.
ToDo erledigt

2024-09-27 09:23 UTC, GrosseNe commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
>  //ToDo: Der Spaltentitel?
ToDo erledigt

2024-09-27 09:23 UTC, GrosseNe commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
>  //ToDo: Was heißt das? Sollten breiter als der Rest der Spalten sein?
ToDo erledigt

2024-09-27 09:23 UTC, GrosseNe commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
>  //ToDo: Welches grundlegendes dreispaltiges Layout? Kommt bisher noch nicht vor
ToDo erledigt.

2024-09-30 11:53 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Die Schnelligkeit und der Aufwand, mit dem Nutzende ihre Ziele erreichen.
Weiterer Vorschlag:
* *Effizienz:*
Die Fähigkeit eines Frontends, mit dem Nutzende ihre Ziele mit möglichst geringem Zeit- und Arbeitsaufwand erreichen.

2024-09-30 12:10 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
>  //TODO: Ist die Verneinung richtig. Wenn ja, earum?
Vorschlag:

*_Dos_*

* Listen sollen inhaltlich so einfach wie möglich gestaltet werden.
* Listeneinträge sollten so kurz wie möglich formuliert sein.
* Listeneinträge sind eindeutig unterscheidbar.
* Wenn Listen viele Einträge haben, so sollten andere Elemente die Durchsuchbarkeit, Filterung oder Kategorisierung ermöglichen.
* Listen können mit unterschiedlichen interaktiven Elementen kombiniert werden, um dem Nutzenden eine Hilfestellung zu bieten.
* Bei einer kleinen Liste kann auch eine Radio-Button-Gruppe genutzt werden.

*_Don'ts_*

* Listeneinträge sollten nie mehrzeilig sein.
* Listeneinträge sollten nicht doppelt vorhanden sein.
* Listen sollten nicht unsortiert und sehr lang sein.
* Listeneinträge mit ganzen Sätzen sollten, wenn möglich, vermieden werden.

2024-09-30 12:34 UTC, GrosseNe commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Die Schnelligkeit und der Aufwand, mit dem Nutzende ihre Ziele erreichen.
Besser: Die Fähigkeit eines Frontends den Nutzenden zu ermöglichen, ihre Ziele mit möglichst geringem Zeit- und Arbeitsaufwand zu erreichen.

2024-09-30 13:21 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Die Schnelligkeit und der Aufwand, mit dem Nutzende ihre Ziele erreichen.
Habe deinen Vorschlag übernommen.

2024-10-01 10:40 UTC, mtpham-collab requested changes

2024-10-01 10:40 UTC, mtpham-collab commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Dabei ist nicht das einzelne Eingabefeld ein Pflichtfeld, sondern das Ausfüllen mindestens einer Option innerhalb einer Eingabefeldgruppe ist verpflichtend.
```suggestion
Dabei ist nicht das einzelne Eingabefeld ein Pflichtfeld, sondern das Ausfüllen mindestens einer Option innerhalb einer Eingabefeldgruppe verpflichtend.

2024-10-01 10:40 UTC, mtpham-collab commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Hier wird deutlich das in einem mehrspaltigen Layout verschiedene Kombinationen an Eingabefeldern in zweispaltiger (horizontaler) Anordnung einer Hauptgruppe (in Lila) unterliegen.
```suggestion
Hier wird deutlich, dass in einem mehrspaltigen Layout verschiedene Kombinationen von Eingabefeldern in zweispaltiger (horizontaler) Anordnung einer Hauptgruppe (in Lila) unterliegen.

2024-10-01 12:08 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Das heißt durch Barrierefreiheit soll sichergestellt werden, dass alle, unabhängig von ihren Fähigkeiten, ein Frontend nutzen können.
Mit und ohne Komma ist hier beides korrekt, lasse das Komma entsprechend weg

2024-10-01 12:12 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Im Folgenden werden die Richtlinien zur Barrierefreiheit gemäß Standards wie WCAG und andere Methoden zur Verbesserung der Zugänglichkeit erläutert.
Ich streiche das Wort "andere", da es hier keinen Mehrwert bringt, sondern nur Verwirrung erzeugt.

2024-10-01 12:15 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Nachfolgend sind die Kontrastverhältnisse aller zur Verfügung stehender Farben abgebildet.
Done

2024-10-01 12:18 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Da dies einen Verstoß gegen die BITV (Barrierefreie-Informationstechnik-Verordnung) bedeuten würde, muss bei der Darstellung von I und l in jeden Fall auf BundesSans zurückgegriffen werden.
Done

2024-10-01 12:18 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +* Buttons mit dem wichtigsten Ziel beziehngsweise mit der am häufigsten genutzten Aktion werden in der Primärfarbe dargestellt.
Done

2024-10-01 12:19 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Das heißt nach der Nutzung eines <<colored-button,kolorierten Buttons>> in der Primärfarbe kann auf die invertierten Buttons umgestiegen werden.
Mit und ohne Komma ist hier beides korrekt, lasse das Komma entsprechend weg

2024-10-01 12:21 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Diese werden beispielsweise innerhalb von Tabellenheadern verwendet zum Sortieren und Filtern der Tabelleninhalte und sehen wie folgt aus:
Done

2024-10-01 12:23 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Hyperlinks sind verlinkte <<text,Texte>> (oder auch <<grafiken>>), die im Wesentlichen als Navigations-Mechanismus dienen, zum Beispiel um neue Fenster mit anderen Inhalten zu öffnen.
Done

2024-10-01 12:24 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Masks können dabei auch frei gestaltet werden und den fachlichen Bedürfnissen entsprechend angepasst werden, beispielsweise für Aktenzeichen.
Done

2024-10-01 12:25 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Textboxen sollten mindestens so groß gestaltetet werden, dass der am häufigsten zu erwartende Inhalt hineinpasst, ohne manuell die Box anzupassen.
Done

2024-10-01 12:27 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +* Listen können mit unterschiedlichen interaktiven Elementen kombiniert werden, um dem Nutzenden eine Hilfestellung zu bieten.
Done

2024-10-01 12:30 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Dabei ist nicht das einzelne Eingabefeld ein Pflichtfeld, sondern das Ausfüllen mindestens einer Option innerhalb einer Eingabefeldgruppe ist verpflichtend.
Done

2024-10-01 12:31 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +Hier wird deutlich das in einem mehrspaltigen Layout verschiedene Kombinationen an Eingabefeldern in zweispaltiger (horizontaler) Anordnung einer Hauptgruppe (in Lila) unterliegen.
Done

2024-10-10 07:49 UTC, sebastianmsg reviewed
Added some changes

2024-10-10 07:49 UTC, sebastianmsg commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +
Add: 
*_Standard-Toolbar_* *WiP*

2024-10-10 08:10 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +=== Hauptfenster
Done, mit kleineren Anpassungen

2024-10-10 08:12 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +
Als zusatz im Header eingebaut: (beinhaltet die Hauptnavigation des isy-hauptfensters)

2024-10-10 08:13 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +
Ist bereits hier inbegriffen: *_Content mit Sidebar_* *WiP* (beinhaltet die Linksnavigation und den Informationsbereich des isy-hauptfensters)

2024-10-10 08:13 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +
Korrekt, entsprechend nicht als eigenes Unterkapitel vorhanden

2024-10-10 08:13 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +[[hauptfenster]]
Verschoben

2024-10-10 08:15 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +[[anwendungsbeispiele]]
Done

2024-10-10 08:15 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +[[objekt-suche]]
Done

2024-10-10 08:16 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +[[leitplanken]]
Umbenannt in Designrichtlinien

2024-10-10 08:19 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +
Done

2024-10-10 08:19 UTC, msg-jstren commented on isy-bedienkonzept-doc/modules/ROOT/pages/bedienkonzept.adoc
> +
Done

2024-10-10 08:29 UTC, sebastianmsg approved these changes
all changes done

2024-10-10 08:42 UTC, mtpham-collab approved these changes

2024-10-10 08:57 UTC, merged